# Este modelo do AWS SAM foi gerado a partir da configuração da sua função. Se sua
# função tiver um ou mais acionadores, observe que os recursos da AWS associados a
# esses acionadores não estão totalmente especificados nesse modelo e incluem
# valores de espaço reservado. Abra esse modelo no AWS Application Composer ou em
# seu IDE favorito e modifique-o para especificar uma aplicação com tecnologia sem
# servidor com outros recursos da AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  updateData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-2:381491959116:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-east-2:381491959116:log-group:/aws/lambda/updateData:*
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DeleteNetworkInterface
                - ec2:DescribeNetworkInterfaces
              Resource: '*'
      SnapStart:
        ApplyOn: None
      VpcConfig:
        SecurityGroupIds:
          - sg-034398b564a92543e
        SubnetIds:
          - subnet-0f8cb45000885be52
          - subnet-01524fe42e9c7c9eb
        Ipv6AllowedForDualStack: false
      Events:
        EventBridgeRule1:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.autoscaling
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - autoscaling.amazonaws.com
                eventName:
                  - UpdateAutoScalingGroup
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
